In [2]:
import numpy as np
import pandas as pd

df=pd.DataFrame({
    'name':['Alice','Bob','Carol','Dave'],
    'score':[82,55,91,48],
    'passed':[True,False,True,False]
})

df

    name  score  passed
0  Alice     82    True
1    Bob     55   False
2  Carol     91    True
3   Dave     48   False

In [3]:
df.shape

(4, 3)

In [4]:
df['name']

0    Alice
1      Bob
2    Carol
3     Dave
Name: name, dtype: object

In [6]:
df[df['score']>60]

    name  score  passed
0  Alice     82    True
2  Carol     91    True

In [17]:
df.dtypes

name      object
score      int64
passed      bool
dtype: object

In [ ]:
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[np.nan,34,29,42],
    'City':['New York','Mumbai','Berlin','London'],
    'Salary':[65000,75000,80000,np.nan]
}
df=pd.DataFrame(data,index=[1,2,3,4]) 
df

    Name   Age      City   Salary
1   John   NaN  New York  65000.0
2   Anna  34.0       NaN  75000.0
3  Peter  29.0    Berlin  80000.0
4  Linda  42.0    London      NaN

In [38]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['Salary']=df['Salary'].fillna(df['Salary'].median())

df

    Name   Age      City   Salary
1   John  34.0  New York  65000.0
2   Anna  34.0       NaN  75000.0
3  Peter  29.0    Berlin  80000.0
4  Linda  42.0    London  75000.0