PANDAS

SERIES

Series is a one dimensional labeled array capable of holding any datatype.The axis labels are collectively called index.

Creating Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
myList=[10,20,30]
arr=np.array(myList)
d={1:10,2:20,3:30}

In [4]:
#Creating series using list
pd.Series(myList,index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
#Creating series from array
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
#Creating series from dictionary   keys->labels  and  value->data
pd.Series(d)

1    10
2    20
3    30
dtype: int64

DATA FRAMES

Data frames are collection of series.

Create a DataFrame

In [ ]:
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,75000,80000,60000]
}
df=pd.DataFrame(data,index=[1,2,3,"hello"])  #index used to name row
df

        Name  Age      City  Salary
1       John   28  New York   65000
2       Anna   34     Paris   75000
3      Peter   29    Berlin   80000
hello  Linda   42    London   60000

In [8]:
data=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',88000],
    ['Linda',42,'London',60000]
]
df2=pd.DataFrame(data)

In [9]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  88000
3  Linda  42    London  60000

In [10]:
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   88000
3  Linda   42    London   60000

Selection and Indexing of Columns

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   88000
3  Linda   42    London   60000

In [12]:
#index does not work but the column name work
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [13]:
df2['Name'][1]

'Anna'

Creating a new column

In [14]:
df2['Designation']=['Doctor','Engineer','Lawyer','Cricketer']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   88000      Lawyer
3  Linda   42    London   60000   Cricketer

In [15]:
#dropping an column
df2.drop(['City','Designation'],axis=1)
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   88000      Lawyer
3  Linda   42    London   60000   Cricketer

In [16]:
#droping an column using inplace
#inplace ensure that the change is made in main table while if inplace is not true then it will give us an idea how the table will look if the particular column is droped
df2.drop('Designation',axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   88000
3  Linda   42    London   60000

In [17]:
df2.drop(['Age','City','Salary'],axis=1)

    Name
0   John
1   Anna
2  Peter
3  Linda

In [18]:
df2.drop(0)   #droping a row

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   88000
3  Linda   42  London   60000

In [19]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [20]:
#Selecting index location iloc in this we pass row index 
df2.iloc[2]

Name       Peter
Age           29
City      Berlin
Salary     88000
Name: 2, dtype: object

Selecting Subset of Rows and Columns

In [21]:
df2.loc[[1,2]][['Name','Age']]

    Name  Age
1   Anna   34
2  Peter   29

Conditional Selection

In [22]:
#select those whose age is >30
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000