In [1]:
import numpy as np
import pandas as pd

Finding Missing Data

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
#find null values
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
#To find number of na values in a column
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [6]:
#To find is every column have a null value or some column is free from it
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing missing data (works on basis of rows)

In [8]:
#Drop all those rows that have atleast one missing value
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
#using Threshold
#remove rows that have na values greater than equal to 3
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling Missing Values

In [ ]:
#fill all the na values with 0 take place column wise
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [11]:
#fill missing values with different entries in different column
values={'A':0,'B':1,'C':3,'D':4}
df.fillna(value=values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  4.0
2  0.0  3  3.0  4.0
3  4.0  4  3.0  4.0
4  5.0  5  3.0  5.0

In [14]:
#fill na with the mean value of column
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0